### ISSUE TITLE
Browser Compatability Issues II

### ISSUE THREAD

**Issue by msrichardson** [ibi-group/trimet-mod-otp#226] opened 2019-07-16 23:24 UTC
(Also see #69)

**Edge**

1. Base map does not render (streets or aerials), however most overlays still work  

1. Origin/destination dropdowns do not work (can type in them, but nothing appears to select from)
  *Can set origin/destination from map and get a trip, but it uses coordinates (doesn't reverse geocode)

_Note:_  the site was not fully tested on Edge, there may be other items not working 

**Internet Explorer**
Nothing renders

This was tried on two different computers, versions for one are: 

- Explorer: 11.885.17134.0

- Edge: 42.17134.1.0 (Microsoft EdgeHTML 17.17134)

**Comment by landonreed** [comment] 2019-07-17 15:16
@msrichardson, I'm not able to reproduce the Edge issue. What site are you testing (e.g. https://trimet-mod-dev.ibi-transit.com/#/)?

![image](https://user-images.githubusercontent.com/2370911/61387552-58c58580-a884-11e9-8c24-635c1684dd3b.png)

**Comment by msrichardson** [comment] 2019-07-17 15:44
Yes. @frankpurcell had similar issues.

**Comment by landonreed** [comment] 2019-07-17 19:00
Can you provide any more information about the operating environment in which you had issues with Edge, @msrichardson? You may have noticed in the screenshot that I was using the same version as you, so any additional information about system OS or screenshots with the developer console open to show potential errors would be helpful. cc @fpurcell

**Comment by fpurcell** [comment] 2019-07-17 19:09
FWIW Landon, I noticed the problems with Edge on my work PC on Monday.  I saw Myleen in a conference room on Tuesday, and that PC was showing the same issue.  The fonts on the left nav were Courier (or some ugly sarif default font), and the map was not rendered. The best I can describe it w/out looking further at the log console (I'm not near my PC now) is that the .css was missing.  

Note that https://modbeta.trimet.org/map-test (which is the version from about 1 week back) did render properly in Edge.  BTW, both map-test and the newer ibi instances of MOD didn't render at all on the IE 11 browser installed on my PC. (That meeting room PC didn't have IE 11 for us to test).

**Comment by msrichardson** [comment] 2019-07-17 20:00
I think the Edge issue is on our end, I'm investigating.

**Comment by msrichardson** [comment] 2019-07-17 20:11
@landonreed re: Edge, I found that this past fall we had a similar issue with the Conveyal site, and the issue was on our end.  I believe it is the same with this new site.  I've submitted a ticket on end to rectify; my apologies for not thinking of that sooner.

**Comment by landonreed** [comment] 2019-08-01 19:54
I believe we can close this now. Let me know if not and we need to reopen, @msrichardson.

**Closed by landonreed** 2019-08-01 19:54 UTC
Labels: browser compatibility, high priority
